# Generated by Django 4.2 on 2026-03-13 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='商户订单号')),
                ('trade_no', models.CharField(blank=True, max_length=64, verbose_name='支付宝交易号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('subject', models.CharField(max_length=200, verbose_name='商品标题')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('vip_card_id', models.IntegerField(verbose_name='VIP卡ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
