"""
Django settings for mymovie project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'account',
    'movie',
    'vip',
    'payment',
    'rest_framework',
    'djoser',
    'django_filters'
]
# stary
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mymovie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mymovie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_movie',
        'USER': 'root',
        'PASSWORD': 'your-password-here',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 后端返回前端的内容
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS':(
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
# 配置JWT
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
}
# 配置邮箱
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 示例使用QQ邮箱SMTP服务器 - 请根据实际情况修改
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'your-email@qq.com'  # 替换为你的邮箱地址
EMAIL_HOST_PASSWORD = 'your-email-password-here'  # 替换为你的邮箱密码或授权码
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True  # QQ邮箱需要使用SSL
DEFAULT_FROM_EMAIL = 'your-email@qq.com'  # 默认发件人
# 邮箱配置 djoser配置
from django.utils.translation import gettext_lazy as _

# 汉化 Djoser 消息
class ChineseMessages:
    INVALID_CREDENTIALS_ERROR = _("用户名或密码错误")
    INACTIVE_ACCOUNT_ERROR = _("账户已被禁用")
    INVALID_TOKEN_ERROR = _("令牌无效")
    INVALID_UID_ERROR = _("用户ID无效或用户不存在")
    STALE_TOKEN_ERROR = _("令牌已过期")
    PASSWORD_MISMATCH_ERROR = _("两次输入的密码不一致")
    USERNAME_MISMATCH_ERROR = _("两次输入的用户名不一致")
    INVALID_PASSWORD_ERROR = _("密码错误")
    EMAIL_NOT_FOUND = _("该邮箱未注册")
    CANNOT_CREATE_USER_ERROR = _("无法创建账户")
# djoser配置
DJOSER = {
    # 密码重置确认URL，用户点击邮件中的链接时将访问此URL
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    # 用户名重置确认URL，用户点击邮件中的链接时将访问此URL
    'USERNAME_RESET_CONFIRM_URL': '#/username/reset/confirm/{uid}/{token}',
    # 用户激活账户的URL，用户点击邮件中的链接时将访问此URL
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    # 密码重置确认URL，用户点击邮件中的链接时将访问此URL
    'PASSWORD_RESET_CONFIRM_URL': 'password_reset/{uid}/{token}',
    # 是否发送激活邮件给新注册用户
    'SEND_ACTIVATION_EMAIL': True,
    # 验证数据库当中是否有密码
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND0 ' : False,
    # 自定义序列化器，如果需要可以在这里指定
    'SET_PASSWORD_RETYPE': True,
    'CONSTANTS': {
        'messages': ChineseMessages,
    },
    'SERIALIZERS': {
        "user_create": "account.serializers.CustomUserCreateSerializer",
        "current_user": "account.serializers.CustomUserSerializer",
        
    },
}

# ALIPAY_APP_ID = ''
# ALIPAY_PRIVATE_KEY = ''
# ALIPAY_PUBLIC_KEY = ''
# ALIPAY_NOTIFY_URL = 'http://localhost:8000/api/payment/alipay_notify/'
# ALIPAY_RETURN_URL = 'http://localhost:8000/api/payment/alipay_return/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True