# Generated by Django 4.2 on 2026-03-08 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProFile',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='用户ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='邮箱')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='头像')),
                ('is_upgrade', models.BooleanField(default=False, verbose_name='是否升级会员')),
                ('upgrade_time', models.DateTimeField(blank=True, null=True, verbose_name='升级时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('upgrade_count', models.IntegerField(default=0, verbose_name='升级次数')),
                ('movie_collect', models.ManyToManyField(related_name='movie_collect', to='movie.movie', verbose_name='看过的电影')),
                ('movie_collection', models.ManyToManyField(related_name='movie_collection', to='movie.movie', verbose_name='电影收藏')),
                ('movie_do', models.ManyToManyField(related_name='movie_do', to='movie.movie', verbose_name='在看的电影')),
                ('movie_wish', models.ManyToManyField(related_name='movie_wish', to='movie.movie', verbose_name='想看的电影')),
                ('movies', models.ManyToManyField(related_name='profile_movies', to='movie.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'ProFile',
            },
        ),
    ]
