# Generated by Django 4.2 on 2026-03-08 04:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '电影分类',
                'verbose_name_plural': '分类管理',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Movie_name', models.CharField(max_length=100, verbose_name='电影名称')),
                ('Movie_director', models.CharField(max_length=100, verbose_name='导演')),
                ('scriptwriter', models.CharField(max_length=100, verbose_name='编剧')),
                ('Movie_actor', models.CharField(max_length=100, verbose_name='演员')),
                ('Movie_type', models.CharField(max_length=100, verbose_name='类型')),
                ('Movie_length', models.IntegerField(verbose_name='片长')),
                ('Movie_score', models.FloatField(verbose_name='评分')),
                ('Movie_describe', models.TextField(blank=True, null=True, verbose_name='电影简介')),
                ('Movie_image', models.ImageField(upload_to='movie_images', verbose_name='电影海报')),
                ('Movie_language', models.CharField(max_length=100, verbose_name='语言')),
                ('Movie_area', models.CharField(choices=[('1', '中国大陆'), ('2', '美国'), ('3', '英国'), ('4', '法国'), ('5', '日本'), ('6', '韩国'), ('7', '其他')], max_length=100, verbose_name='地区')),
                ('Movie_release_date', models.DateField(default=django.utils.timezone.now, verbose_name='上映日期')),
                ('Movie_duration', models.CharField(max_length=100, verbose_name='时长')),
                ('Movie_douban_score', models.CharField(max_length=100, verbose_name='豆瓣评分')),
                ('Movie_subtitle', models.CharField(max_length=100, verbose_name='字幕')),
                ('Movie_update_info', models.CharField(max_length=100, verbose_name='更新信息')),
                ('Movie_Storage', models.TextField(blank=True, default='', help_text='每个网盘信息占一行，每个字段用网盘名:网址 提取码:字符组成(无提取码不写)。如 百度网盘:http:/www.baidu.com 提取码:8888', max_length=200, null=True, verbose_name='网盘信息')),
                ('Movie_is_hot', models.CharField(choices=[('1', '是'), ('2', '否')], default='2', max_length=1, verbose_name='是否热门')),
                ('Movie_is_top', models.CharField(choices=[('1', '是'), ('2', '否')], default='2', max_length=1, verbose_name='是否置顶')),
                ('Movie_is_free', models.CharField(choices=[('1', '是'), ('2', '否')], default='2', max_length=1, verbose_name='是否免费')),
                ('Movie_is_show', models.CharField(choices=[('1', '是'), ('2', '否')], default='1', max_length=1, verbose_name='是否显示')),
                ('Movie_clear_rate', models.CharField(choices=[('3', '720p'), ('4', '1080p'), ('5', '4k')], default='1', max_length=1, verbose_name='清晰度')),
                ('Movie_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category', verbose_name='电影分类')),
            ],
            options={
                'verbose_name': '电影信息',
                'verbose_name_plural': '电影管理',
                'db_table': 'Movie',
                'ordering': ['Movie_name'],
            },
        ),
    ]
